### ISSUE TITLE
How to properly add X-Socket-ID header?

### ISSUE THREAD

**Issue by BizzyBob** [chancezeus/angular-laravel-echo#5]
Laravel can take advantage of the X-Socket-ID header if provided on each request.  How should I properly add this?

Of course I'm using Angular...  I see you have the `registerjQueryAjaxSetup()` method, but when I attempt to use like:

this.EchoService.echo.registerjQueryAjaxSetup(), I get:

    ERROR in {file_path} error TS2341: Property 'echo' is private and only accessible within class 'EchoService'.

I don't think the correct thing to do is change to public, but I try anyhow and I get no errors, but the header is not applied.

I also try applying headers manually, but not sure how if I cannot access the echo instance.

Thanks!

**Comment by chancezeus** [comment]
This depends on the backend used for the old (deprecated) HttpModule (Http service) this is not easy to provide (I recommend checking the docs for the module on how this can be done manually). For the new HttpClient I can create an interceptor that get's registered when the AngularLaravelEchoModule.forRoot method is called and which automatically injects the header, this however will also cause the service to be instantiated immediately upon registration (since it'll be injected into the interceptor constructor) instead of when requested for the first time by a component.

**Comment by chancezeus** [comment]
I just uploaded a new build which includes an interceptor, if you've been using the forRoot method to import and configure the module it should be automatically picked up as soon as you update to 1.1.9 or 2.0.9 (depending on rxjs/angular version). Otherwise you'll have to add it manually (see the docs page for an example).

**Comment by BizzyBob** [comment]
awesome, I will check it out this weekend.  Thank you!

**Comment by BizzyBob** [comment]
Any reason I would start getting this error?

`ERROR in ../node_modules/angular-laravel-echo/dist/src/module.d.ts(1,37): error TS2307: Cannot find module '@angular/core'.
../node_modules/angular-laravel-echo/dist/src/services/lib.service.d.ts(1,40): error TS2307: Cannot find module '@angular/core'.
../node_modules/angular-laravel-echo/dist/src/services/lib.service.d.ts(2,28): error TS2307: Cannot find module 'rxjs'.`


I'm noticing that it's looking at the wrong files here, my project folder is omitted:

`ERROR in ../node_modules/angular-laravel-echo/dist/angular-laravel-echo.js
Module not found: Error: Can't resolve '@angular/common' in '/Users/Bob/BLScript/node_modules/angular-laravel-echo/dist'`

`ERROR in ../node_modules/angular-laravel-echo/dist/angular-laravel-echo.js
Module not found: Error: Can't resolve '@angular/common' in '/Users/Bob/BLScript/**PROJECT_NAME**/node_modules/angular-laravel-echo/dist'`

**Comment by chancezeus** [comment]
One of the previous releases did have an error from my side during upload to npm (it included the entire source root instead of only the dist folder), which might give problems during update. Easiest fix is to remove the "node_modules/angular-laravel-echo" folder and rerun `npm i --save angular-laravel-echo`, it should install the latest version (if you are still using angular@5, you should run `npm i --save angular-laravel-echo@^1.1.0` to get the latest angular 5 compatible version, I try (for the time being) to keep both in sync since current ionic stable is still using angular 5)

**Comment by BizzyBob** [comment]
I'm using angular 6.1;  I noticed that when reverting back to version 2.0.6 it works fine. After upgrading to 2.0.7 the issue occurs.

**Comment by BizzyBob** [comment]
Thanks again for your attention.  I'll work on getting the code sample.

**Comment by chancezeus** [comment]
> I'm using angular 6.1; I noticed that when reverting back to version 2.0.6 it works fine. After upgrading to 2.0.7 the issue occurs.

Latest version (and the one that includes the Interceptor) is 2.0.10, 2.0.7 is actually the one with the broken update...

**Comment by BizzyBob** [comment]
Yes, I started by trying 2.0.10 which gave the error when running `ng serve`.  So, I went back to my the version I started with 2.0.3, which works fine.  Then I tried every version and found they all work up until 2.0.7.

**Comment by BizzyBob** [comment]
I just now tried deleting the `angular-laravel-echo` folder.

running `npm install angular-laravel-echo`; which installs v2.0.10
running `ng serve`; which produces error about not being able to locate @angular/common

**Comment by BizzyBob** [comment]
if i run `npm install angular-laravel-echo@2.0.3` then running `ng serve` works fine with no problem.

**Comment by chancezeus** [comment]
I just created a new (clean) angular project using `ng new project` and added the module to AppModule and the service to the component and it still works as expected (besides an error caused by ng cli/builder), so I will really need a reproduction case to trace the issue...

**Comment by BizzyBob** [comment]
yeah, I basically did the same thing and it worked for me as well.  I'll see what's weird about my use case.

**Comment by chancezeus** [comment]
In any case:
`../node_modules/angular-laravel-echo/dist/` should be `../node_modules/angular-laravel-echo/` (ie. without the dist, the `/dist/` means it is actually using the wrong (broken) version)...

**Comment by BizzyBob** [comment]
ha ha, I just figured out that was my problem and was coming back here to report it!  Yes, it's working now.  Thanks for taking a look. :-)

**Comment by BizzyBob** [comment]
Now I can finally take a look at that Interceptor that adds the x-socket-id header!

**Comment by BizzyBob** [comment]
Interceptor works great..! :-) THANKS!
